config/routes.rb
Rails.application.routes.draw do
  resources :campos
  resources :fields

   root 'campos#index'

end

app/models/campo.rb
class Campo < ActiveRecord::Base
end

app/models/field.rb
class Field < ActiveRecord::Base

  extend ActsAsTree::TreeWalker

  acts_as_tree order: 'layout_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campos_controller.rb
class CamposController < ApplicationController
  before_action :set_campo, only: [:show, :edit, :update, :destroy]

  # GET /campos
  # GET /campos.json
  def index
    @campos = Campo.all
  end

  # GET /campos/1
  # GET /campos/1.json
  def show
  end

  # GET /campos/new
  def new
    @campo = Campo.new
  end

  # GET /campos/1/edit
  def edit
  end

  # POST /campos
  # POST /campos.json
  def create
    @campo = Campo.new(campo_params)

    respond_to do |format|
      if @campo.save
        format.html { redirect_to @campo, notice: 'Campo was successfully created.' }
        format.json { render :show, status: :created, location: @campo }
      else
        format.html { render :new }
        format.json { render json: @campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campos/1
  # PATCH/PUT /campos/1.json
  def update
    respond_to do |format|
      if @campo.update(campo_params)
        format.html { redirect_to @campo, notice: 'Campo was successfully updated.' }
        format.json { render :show, status: :ok, location: @campo }
      else
        format.html { render :edit }
        format.json { render json: @campo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campos/1
  # DELETE /campos/1.json
  def destroy
    @campo.destroy
    respond_to do |format|
      format.html { redirect_to campos_url, notice: 'Campo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campo
      @campo = Campo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campo_params
      params.require(:campo).permit(:layout_id, :number_field, :name, :parent, :level)
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    #@datos = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:id, :layout_id, :number_field, :fieldtype_id, :name, :changeable, :length, :parent, :level, :alias)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campos_helper.rb
module CamposHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/campos/_form.html.erb
<%= form_for(@campo) do |f| %>
  <% if @campo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campo.errors.count, "error") %> prohibited this campo from being saved:</h2>

      <ul>
      <% @campo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :layout_id %><br>
    <%= f.number_field :layout_id %>
  </div>
  <div class="field">
    <%= f.label :number_field %><br>
    <%= f.number_field :number_field %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.check_box :parent %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campos/edit.html.erb
<h1>Editing Campo</h1>

<%= render 'form' %>

<%= link_to 'Show', @campo %> |
<%= link_to 'Back', campos_path %>

app/views/campos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campos</h1>

<table>
  <thead>
    <tr>
      <th>Layout</th>
      <th>Number field</th>
      <th>Name</th>
      <th>Parent</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campos.each do |campo| %>
      <tr class="level<%= campo.level %> " data-depth="<%= campo.level %>">
        <% if campo.parent? %>
            <td><span class="toggle "><%= campo.layout_id %></td>
        <% else %>
            <td><%= campo.layout_id %></td>
        <% end %>
        <td><%= campo.number_field %></td>
        <td><%= campo.name %></td>
        <td><%= campo.parent %></td>
        <td><%= campo.level %></td>
        <td><%= link_to 'Show', campo %></td>
        <td><%= link_to 'Edit', edit_campo_path(campo) %></td>
        <td><%= link_to 'Destroy', campo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campo', new_campo_path %>

app/views/campos/new.html.erb
<h1>New Campo</h1>

<%= render 'form' %>

<%= link_to 'Back', campos_path %>

app/views/campos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Layout:</strong>
  <%= @campo.layout_id %>
</p>

<p>
  <strong>Number field:</strong>
  <%= @campo.number_field %>
</p>

<p>
  <strong>Name:</strong>
  <%= @campo.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @campo.parent %>
</p>

<p>
  <strong>Level:</strong>
  <%= @campo.level %>
</p>

<%= link_to 'Edit', edit_campo_path(@campo) %> |
<%= link_to 'Back', campos_path %>

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :layout_id %><br>
    <%= f.number_field :layout_id %>
  </div>
  <div class="field">
    <%= f.label :number_field %><br>
    <%= f.number_field :number_field %>
  </div>
  <div class="field">
    <%= f.label :fieldtype_id %><br>
    <%= f.number_field :fieldtype_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :changeable %><br>
    <%= f.check_box :changeable %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :parent %><br>
    <%= f.check_box :parent %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :alias %><br>
    <%= f.text_field :alias %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<div class="inbox-content">
  <!--<table class="table table-hover table-striped table-responsive">-->
  <table class="table table-striped table-responsive" id="tableTree">
    <thead>
    <tr>
      <th>Id</th>
      <th>Layout</th>
      <th>Number field</th>
      <th>Fieldtype</th>
      <th>Name</th>
      <th>Changeable</th>
      <th>Length</th>
      <th>Parent</th>
      <th>Level</th>
      <th>Alias</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @datos = Field.all %>
    <% @datos.each do |field| %>
        <tr data-depth="<%= field.level %>" class="collapse level<%= field.level %>">
          <% if field.parent? %>
              <td><span class="toggle collapse"><%= field.id %></td>
          <% else %>
              <td><%= field.id %></td>
          <% end %>
          <td><%= field.layout_id %></td>
          <td><%= field.number_field %></td>
          <td><%= field.fieldtype_id %></td>
          <td><%= field.name %></td>
          <td><%= field.changeable %></td>
          <td><%= field.length %></td>
          <td><%= field.parent_id %></td>
          <td><%= field.level %></td>
          <td><%= field.alias %></td>
          <td align="right">

            <%= link_to '<button class="btn btn-primary dim" type="button"><i class="fa fa-search"></i></button>'.html_safe, field %>
            <%= link_to '<button class="btn btn-warning dim" type="button"><i class="fa fa-pencil"></i></button> '.html_safe, edit_field_path(field) %>
            <%= link_to '<button class="btn btn-danger dim" type="button"><i class="fa fa-trash-o"></i></button> '.html_safe, field, method: :delete, data: {confirm: 'Are you sure?'} %>

          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @field.id %>
</p>

<p>
  <strong>Layout:</strong>
  <%= @field.layout_id %>
</p>

<p>
  <strong>Number field:</strong>
  <%= @field.number_field %>
</p>

<p>
  <strong>Fieldtype:</strong>
  <%= @field.fieldtype_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Changeable:</strong>
  <%= @field.changeable %>
</p>

<p>
  <strong>Length:</strong>
  <%= @field.length %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @field.parent %>
</p>

<p>
  <strong>Level:</strong>
  <%= @field.level %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @field.alias %>
</p>

<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pruebas1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Main css styles -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= yield :stylesheet %>
  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



<%= yield :stylesheet %>

<%= yield :javascript %>
</body>
</html>